BREAKING CHANGE: Refactor components
AlaskaAirlines/OrionStatelessComponents__ods-inputoptions pull request #8
Opened 2019-11-19 23:54 UTC by blackfalcon

# Alaska Airlines Pull Request

Update currently released ods-inputoptions with two new components to reduce the complexity of support. 

**Fixes:** #4

## Summary:

The core features of ods-inputoptions will be preserved and with this update will release two new components for use. ods-inputoption-group and ods-inputoption.

ods-inputoption-group will be a wrapper component used within the HTML and ods-inputoption cab be used repeatedly as elements within the slot of ods-inputoption-group. This will allow for a less complex API of the component as well as give developers direct access to the inner components. 

Worked within the scope of this update also includes support for a light DOM version of the component. 

## Type of change:

Please delete options that are not relevant.

- [x] New capability 
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate) 

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 

**Thank you for your submission!**<br>
-- Orion Design System Team

2019-12-17 00:35 UTC, blackfalcon commented on src/ods-inputoption-group.js
> +        class="${classMap(groupClasses)}">
I really like this. Just started looking at classMap too and seeing how other components can be refactored.

2020-04-28 19:10 UTC, AuroDesignSystem requested changes
Overall, looking great. But there is an issue with the a11y tabbing states. The user will tab INTO a radio button set and use the ARROW KEYS to move between buttons. 

Then the user will tab OUT of the set. 

The way this is currently working, the a11y user is trapped.  Please review the a11y interaction on the MASTER branch. 

There is the same issue with checkboxes. 

Tabbing appears to be totally broken with light DOM versions?

2020-04-28 19:28 UTC, AuroDesignSystem requested changes

2020-04-28 19:28 UTC, ecommerceUXdesign commented on demo/index.html
>      <script type="module" src="../src/ods-inputoptions.js"></script>
ods-inputoptions should be removed from this version. This is a BREAKING CHANGE and there is no need to support this version any longer.

2020-04-28 19:36 UTC, AuroDesignSystem requested changes
There seems to be a general issue with the tabbing. In the examples on the demo page, when I click on the LABEL, the first option is not selected? 

Please see https://auro-prod-site-w2.azurewebsites.net/ods-options for the initial version of this component. 

There seems to be some wonkyness with the CSS selector.

2020-05-04 18:02 UTC, AuroDesignSystem submitted a review, later dismissed

2020-05-04 18:11 UTC, AuroDesignSystem approved these changes

2020-05-04 18:11 UTC, merged

2020-05-04 18:13 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/ods-inputoptions/v/2.0.0)
- [GitHub release](https://github.com/AlaskaAirlines/ods-inputoptions/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: